### ISSUE TITLE
Update Docker files

### ISSUE THREAD

**Issue by evroon** [twhui/LiteFlowNet3#2]
The Dockerfile in docker/standalone/gpu still uses Ubuntu 14.04, which is quite outdated. It would be useful to update these to Ubuntu 20.04. Also, the Dockerfile currently does not work, I get the following error when building the image:

```
Err https://developer.download.nvidia.com  Packages
  gnutls_handshake() failed: Handshake failed
Get:24 http://archive.ubuntu.com trusty/multiverse amd64 Packages [169 kB]
Err https://developer.download.nvidia.com  Packages
  gnutls_handshake() failed: Handshake failed
W: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/Packages  gnutls_handshake() failed: Handshake failed

W: Failed to fetch https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/Packages  gnutls_handshake() failed: Handshake failed

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

It seems that fetching the cuda repo using HTTPS does not work on Ubuntu 14.04, as discussed [here](https://github.com/NVIDIA/nvidia-docker/issues/714).

**Comment by twhui** [comment]
I haven't provided any docker files in this repo. Where have you found them?

**Comment by evroon** [comment]
Sorry, I was talking about your original liteflownet repo, where you have for example this Dockerfile: https://www.github.com/twhui/LiteFlowNet/tree/master/docker%2Fstandalone%2Fgpu%2FDockerfile

**Comment by twhui** [comment]
The docker folder is from FlowNet (https://github.com/lmb-freiburg/flownet2). I didn't use it. You may simply ignore it.

**Comment by evroon** [comment]
Ah okay. Thanks!
