### ISSUE TITLE
Is there a pytorch implementation of LiteFlowNet3?

### ISSUE THREAD

**Issue by littlespray** [twhui/LiteFlowNet3#3]
Hi,

Thank you for your great work! The results are really amazing. Could you please tell me if there is a pytorch version of LiteFlowNet3? It would be very helpful for someone who is very interested in your outstanding work but not proficient in Caffe. Thank you very much.

With regard,
Littlespray

**Comment by twhui** [comment]
Unfortunately, I have not implemented LiteFlowNet3 in pytorch yet.

**Comment by lhao0301** [comment]
@littlespray  A pytorch implementation of the liteflownet3-inference can be found [here](https://github.com/lhao0301/pytorch-liteflownet3)
