### ISSUE TITLE
bad result on repetitive pattern

### ISSUE THREAD

**Issue by lhao0301** [twhui/LiteFlowNet3#4]
Thanks for your wonderful code! 
And the idea to solve the "Correspondence Ambiguity" problem via processing the cost-volume is inspiring.

I extract two frames from a demo video to estimate the optical flow. The result is more sharp than LiteFlowNet2. However, it performs worse than LiteFlowNet2 in the region with repetitive pattern. And both LiteFlowNet3 and LiteFlowNet2 performs not well for repetitive pattern.

left_frame:
![image](https://user-images.githubusercontent.com/10356897/111953537-bca45500-8b21-11eb-8b53-b3499c894784.png)

righe_frame:
![image](https://user-images.githubusercontent.com/10356897/111953665-e65d7c00-8b21-11eb-88cd-af8c90ba7c57.png)

LiteFlowNet2-ft-sintel(motion_x & motion_y, respectively):
![image](https://user-images.githubusercontent.com/10356897/111953496-abf3df00-8b21-11eb-9f13-6d83e4482324.png)

LiteFlowNet3-ft-sintel:
![image](https://user-images.githubusercontent.com/10356897/111953462-9da5c300-8b21-11eb-9603-7b8f4c09c3fa.png)

**Comment by twhui** [comment]
Try to reduce your input size, say similar to Sintel images

**Comment by lhao0301** [comment]
It just works~

I try some more cases and meet the same problem, unfortunately, in spite of different resolution. [Actually, the motion between left and right image is small enough. Hence, downsamping image resolution to be similar to sintel images is not so important?]

One of such cases is as follow:
![008_half](https://user-images.githubusercontent.com/10356897/112831734-f39cdc80-90c6-11eb-8266-b3686a8adb7b.png)
![009_half](https://user-images.githubusercontent.com/10356897/112831749-fa2b5400-90c6-11eb-84fa-bb87906aade5.png)
![008_probe](https://user-images.githubusercontent.com/10356897/112831771-ff889e80-90c6-11eb-9f68-515d70063e73.png)

@twhui

**Comment by lhao0301** [comment]
I try some more cases and meet the same problem, unfortunately, in spite of different resolution.

One of such cases is as follow:
![008_half](https://user-images.githubusercontent.com/10356897/112831734-f39cdc80-90c6-11eb-8266-b3686a8adb7b.png)
![009_half](https://user-images.githubusercontent.com/10356897/112831749-fa2b5400-90c6-11eb-84fa-bb87906aade5.png)
![008_probe](https://user-images.githubusercontent.com/10356897/112831771-ff889e80-90c6-11eb-9f68-515d70063e73.png)

**Comment by twhui** [comment]
I will address this issue in the next release of my research.

**Comment by lhao0301** [comment]
Can u also provide the model trained on flyingthings3d?

Most video in daily life is of great diversity and it looks difficult to fit specific video by retraining model one by one.

**Comment by twhui** [comment]
I will address this issue in the next release of my research.
