### ISSUE TITLE
Report Error:  CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by StrugglingForBetter** [twhui/LiteFlowNet3#6]
when run  this command
python test_batch.py img1.txt img2.txt results

it reports error message: 
Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0)  CUDNN_STATUS_BAD_PARAM

Can you help me with this problem? Thanks

**Comment by twhui** [comment]
This  is usually related to incorrect CUDA and cuDNN versions.

**Comment by StrugglingForBetter** [comment]
> This is usually related to incorrect CUDA and cuDNN versions.

Hi, Thanks for your reply. I emailled you but my email was rejected automatically. I don't know why.

For this problem, I followed instructions presented on this page:
https://github.com/twhui/LiteFlowNet#Prerequisite

I use CUDA 8.0, cuDNN 5.1, which are all downloaded from nvidia official website.
